import esbuild from "esbuild";
import { builtinModules } from "node:module";
import process from "node:process";
import { fileURLToPath } from "node:url";

const production = process.argv[2] === "production";
const sourceMap = production ? false : "inline";
const projectPath = (relativePath) => fileURLToPath(new URL(relativePath, import.meta.url));

const javascript = await esbuild.context({
  banner: {
    js: "/* Generated by the Homepage Studio build. */"
  },
  entryPoints: [projectPath("./src/main.ts")],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    ...builtinModules
  ],
  format: "cjs",
  target: "es2021",
  treeShaking: true,
  minify: production,
  sourcemap: sourceMap,
  outfile: projectPath("./main.js"),
  logLevel: "info"
});

const styles = await esbuild.context({
  banner: {
    css: "/* Generated by the Homepage Studio build. */"
  },
  entryPoints: [projectPath("./src/styles/index.css")],
  bundle: true,
  minify: production,
  sourcemap: sourceMap,
  outfile: projectPath("./styles.css"),
  logLevel: "info"
});

if (production) {
  await Promise.all([
    javascript.rebuild(),
    styles.rebuild()
  ]);
  await Promise.all([
    javascript.dispose(),
    styles.dispose()
  ]);
} else {
  await Promise.all([
    javascript.watch(),
    styles.watch()
  ]);
}
